services:
  redis:
    build:
      context: ./redis-like
    networks:
      - internal
    expose:
      - 4000

  kv:
    build:
      context: ./kv-server
    environment:
      - REDIS_URL=http://redis:4000
    ports:
      - 8080:3000
    depends_on:
      - redis
    networks:
      - internal

networks:
  internal:
    driver: bridge
