version: "3.8"

services:
  redis:
    build:
      context: ./redis-like
      dockerfile: Dockerfile.redis
    expose:
      - "4000"
    networks:
      - internal

  kv:
    build:
      context: ./kv-server
      dockerfile: Dockerfile.kv.dev
    ports:
      - "8080:3000"
    environment:
      REDIS_URL: http://redis:4000
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - ./kv-server:/app

networks:
  internal:
