FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
COPY build.mjs ./
RUN npm ci

COPY src ./src
RUN npm run build

# === Production (slim) stage ===
FROM node:20-alpine AS prod

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

EXPOSE 3000
CMD ["node", "dist/server.js"]
